import { Brand, Category, Product } from '@/types';

export const brands: Brand[] = [
  { id: 'berger', name: 'Berger', logo: '/images/brands/berger.png', description: 'Premium quality paints for every surface', productCount: 45 },
  { id: 'brighto', name: 'Brighto', logo: '/images/brands/brighto.png', description: 'Bright and lasting colors for your home', productCount: 32 },
  { id: 'choice', name: 'Choice', logo: '/images/brands/choice.png', description: 'Your choice for quality paints', productCount: 28 },
  { id: 'diamond', name: 'Diamond', logo: '/images/brands/diamond.png', description: 'Shine like a diamond with our paints', productCount: 35 },
  { id: 'gobis', name: "Gobi's", logo: '/images/brands/gobi\'s.png', description: 'Traditional quality, modern finish', productCount: 37 },
  { id: 'ocean', name: 'Ocean', logo: '/images/brands/ocean.png', description: 'Deep colors inspired by the ocean', productCount: 18 },
  { id: 'reliable', name: 'Reliable', logo: '/images/brands/reliable.png', description: 'Reliability you can trust', productCount: 11 },
  { id: 'reliance', name: 'Reliance', logo: '/images/brands/reliance.png', description: 'Building trust through quality', productCount: 20 },
  { id: 'rozzi', name: 'Rozzi', logo: '/images/brands/rozzi.png', description: 'Italian-inspired elegance', productCount: 15 },
  { id: 'saasi', name: 'Saasi', logo: '/images/brands/saasi.png', description: 'Colors that speak for themselves', productCount: 30 },
];

export const categories: Category[] = [
  {
    id: 'decorative',
    name: 'Decorative',
    slug: 'decorative',
    image: '/images/categories/decorative.jpg',
    description: 'Transform your interiors with our premium decorative paints. Perfect for walls, ceilings, and accent features.',
    productCount: 120,
  },
  {
    id: 'industrial',
    name: 'Industrial',
    slug: 'industrial',
    image: '/images/categories/industrial.jpg',
    description: 'Heavy-duty industrial coatings for factories, warehouses, and commercial spaces.',
    productCount: 85,
  },
  {
    id: 'auto',
    name: 'Auto',
    slug: 'auto',
    image: '/images/categories/Auto-Finish.jpg',
    description: 'Professional automotive finishes for cars, bikes, and all vehicles.',
    productCount: 65,
  },
  {
    id: 'projects',
    name: 'Projects',
    slug: 'projects',
    image: '/images/categories/project.png',
    description: 'Complete paint solutions for construction projects and large-scale applications.',
    productCount: 95,
  },
];

export const products: Product[] = [
  // Berger Products
  {
    id: 'berger-elegance-emulsion',
    name: 'Elegance Emulsion',
    brand: 'Berger',
    category: 'decorative',
    price: 4500,
    originalPrice: 5200,
    image: '/images/products/berger/elegance emulsion.png',
    description: 'Premium interior emulsion with silky smooth finish',
    coverage: '120-140 sq ft/liter',
    finishType: 'Matt',
    inStock: true,
    loyaltyPoints: 45,
  },
  {
    id: 'berger-silk-emulsion',
    name: 'Silk Emulsion',
    brand: 'Berger',
    category: 'decorative',
    price: 5200,
    originalPrice: 5800,
    image: '/images/products/berger/silk emulsion.png',
    description: 'Luxurious silk finish for elegant interiors',
    coverage: '100-120 sq ft/liter',
    finishType: 'Silk',
    inStock: true,
    loyaltyPoints: 52,
  },
  {
    id: 'berger-weather-coat',
    name: 'Weather Coat Glow 365',
    brand: 'Berger',
    category: 'decorative',
    price: 6500,
    image: '/images/products/berger/weather coat glow 365.webp',
    description: 'All-weather exterior paint with UV protection',
    coverage: '80-100 sq ft/liter',
    finishType: 'Gloss',
    inStock: true,
    loyaltyPoints: 65,
  },
  {
    id: 'berger-super-gloss-enamel',
    name: 'Super Gloss Enamel',
    brand: 'Berger',
    category: 'decorative',
    price: 3800,
    image: '/images/products/berger/super gloss enamel.png',
    description: 'High gloss enamel for wood and metal surfaces',
    coverage: '130-150 sq ft/liter',
    finishType: 'High Gloss',
    inStock: true,
    loyaltyPoints: 38,
  },
  {
    id: 'berger-red-oxide-primer',
    name: 'Red Oxide Primer',
    brand: 'Berger',
    category: 'industrial',
    price: 2800,
    image: '/images/products/berger/Red-Oxide-Primer.webp',
    description: 'Anti-corrosive primer for metal surfaces',
    coverage: '100-120 sq ft/liter',
    finishType: 'Matt',
    inStock: true,
    loyaltyPoints: 28,
  },
  {
    id: 'berger-woodpro-lacquer',
    name: 'WoodPro PU Lacquer',
    brand: 'Berger',
    category: 'decorative',
    price: 4200,
    image: '/images/products/berger/woodpro pu lacquer.webp',
    description: 'Premium polyurethane lacquer for wood finishing',
    coverage: '140-160 sq ft/liter',
    finishType: 'Gloss',
    inStock: true,
    loyaltyPoints: 42,
  },
  {
    id: 'berger-aluminum-paint',
    name: 'Aluminum Paint',
    brand: 'Berger',
    category: 'industrial',
    price: 3200,
    image: '/images/products/berger/Aluminum-Paint.webp',
    description: 'Heat-resistant aluminum paint for industrial use',
    coverage: '80-100 sq ft/liter',
    finishType: 'Metallic',
    inStock: true,
    loyaltyPoints: 32,
  },
  {
    id: 'berger-chlorinated-rubber',
    name: 'Chlorinated Rubber Base Paint',
    brand: 'Berger',
    category: 'industrial',
    price: 5500,
    image: '/images/products/berger/Chlorinated-Rubber-Base-Paint.webp',
    description: 'Chemical-resistant coating for industrial floors',
    coverage: '60-80 sq ft/liter',
    finishType: 'Semi-Gloss',
    inStock: true,
    loyaltyPoints: 55,
  },
  // Diamond Products
  {
    id: 'diamond-ace-emulsion',
    name: 'Ace Acrylic Plastic Emulsion',
    brand: 'Diamond',
    category: 'decorative',
    price: 3500,
    image: '/images/products/diamond/ace acrylic-plastic-emulsion.webp',
    description: 'Durable acrylic emulsion for interior walls',
    coverage: '120-140 sq ft/liter',
    finishType: 'Matt',
    inStock: true,
    loyaltyPoints: 35,
  },
  {
    id: 'diamond-ace-durasilk',
    name: 'Ace Durasilk Emulsion',
    brand: 'Diamond',
    category: 'decorative',
    price: 4800,
    image: '/images/products/diamond/ace Durasilk emulsion.webp',
    description: 'Silk finish emulsion with superior washability',
    coverage: '100-120 sq ft/liter',
    finishType: 'Silk',
    inStock: true,
    loyaltyPoints: 48,
  },
  {
    id: 'diamond-weather-defender',
    name: 'Ace Weather Defender',
    brand: 'Diamond',
    category: 'decorative',
    price: 5800,
    image: '/images/products/diamond/ace weather defender.webp',
    description: 'Premium exterior paint with weather protection',
    coverage: '80-100 sq ft/liter',
    finishType: 'Matt',
    inStock: true,
    loyaltyPoints: 58,
  },
  {
    id: 'diamond-super-gloss',
    name: 'Ace Super Gloss Enamel',
    brand: 'Diamond',
    category: 'decorative',
    price: 3200,
    image: '/images/products/diamond/ace super gloss enamel.webp',
    description: 'Premium gloss enamel for wood and metal',
    coverage: '130-150 sq ft/liter',
    finishType: 'High Gloss',
    inStock: true,
    loyaltyPoints: 32,
  },
  {
    id: 'diamond-roof-coat',
    name: 'Roof Coat',
    brand: 'Diamond',
    category: 'industrial',
    price: 4500,
    image: '/images/products/diamond/roof coat.webp',
    description: 'Waterproof coating for roof surfaces',
    coverage: '50-60 sq ft/liter',
    finishType: 'Matt',
    inStock: true,
    loyaltyPoints: 45,
  },
  // Ocean Products
  {
    id: 'ocean-emulsion',
    name: 'Ocean Emulsion',
    brand: 'Ocean',
    category: 'decorative',
    price: 2800,
    image: '/images/products/ocean/ocean emulsion.png',
    description: 'Affordable quality emulsion for interiors',
    coverage: '120-140 sq ft/liter',
    finishType: 'Matt',
    inStock: true,
    loyaltyPoints: 28,
  },
  {
    id: 'ocean-lustre-enamel',
    name: 'Ocean Lustre Enamel',
    brand: 'Ocean',
    category: 'decorative',
    price: 2500,
    image: '/images/products/ocean/ocean Lustre-enamel.png',
    description: 'Lustrous enamel for smooth finishes',
    coverage: '130-150 sq ft/liter',
    finishType: 'Semi-Gloss',
    inStock: true,
    loyaltyPoints: 25,
  },
  {
    id: 'ocean-metallic-enamel',
    name: 'Ocean Metallic Enamel',
    brand: 'Ocean',
    category: 'auto',
    price: 3500,
    image: '/images/products/ocean/ocean metallic enamel.png',
    description: 'Metallic finish enamel for automotive use',
    coverage: '100-120 sq ft/liter',
    finishType: 'Metallic',
    inStock: true,
    loyaltyPoints: 35,
  },
  {
    id: 'ocean-red-oxide',
    name: 'Ocean Red Oxide Primer',
    brand: 'Ocean',
    category: 'industrial',
    price: 2200,
    image: '/images/products/ocean/ocean RED oxide primer.png',
    description: 'Protective primer for metal surfaces',
    coverage: '100-120 sq ft/liter',
    finishType: 'Matt',
    inStock: true,
    loyaltyPoints: 22,
  },
  // Reliance Products
  {
    id: 'reliance-semi-plastic',
    name: 'Reliance Semi Plastic Emulsion',
    brand: 'Reliance',
    category: 'decorative',
    price: 2600,
    image: '/images/products/reliance/Reliance-Semi-Plastic-Emulsion.png',
    description: 'Economy emulsion with good coverage',
    coverage: '120-140 sq ft/liter',
    finishType: 'Matt',
    inStock: true,
    loyaltyPoints: 26,
  },
  {
    id: 'reliance-weather-guard',
    name: 'Reliance Weather Guard',
    brand: 'Reliance',
    category: 'decorative',
    price: 4200,
    image: '/images/products/reliance/Reliance-Weather-Guard.png',
    description: 'Weather-resistant exterior paint',
    coverage: '80-100 sq ft/liter',
    finishType: 'Matt',
    inStock: true,
    loyaltyPoints: 42,
  },
  {
    id: 'reliance-matt-enamel',
    name: 'Reliance Matt Enamel',
    brand: 'Reliance',
    category: 'decorative',
    price: 2800,
    image: '/images/products/reliance/Reliance-Matt-Enamel.png',
    description: 'Matt finish enamel for wood and metal',
    coverage: '130-150 sq ft/liter',
    finishType: 'Matt',
    inStock: true,
    loyaltyPoints: 28,
  },
  {
    id: 'reliance-red-oxide',
    name: 'Reliance Red Oxide Primer',
    brand: 'Reliance',
    category: 'industrial',
    price: 2000,
    image: '/images/products/reliance/Reliance-Red-Oxide-Primer.png',
    description: 'Anti-rust primer for iron and steel',
    coverage: '100-120 sq ft/liter',
    finishType: 'Matt',
    inStock: true,
    loyaltyPoints: 20,
  },
  // Gobi's Products
  {
    id: "gobis-clear-lacquer",
    name: "Clear Lacquer",
    brand: "Gobi's",
    category: "decorative",
    price: 3934,
    image: "/images/products/gobi's/clear_lacquer-removebg-preview.png",
    description: "Premium quality Clear Lacquer",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 39
  },
  {
    id: "gobis-gobi-s-gold-weather-guard",
    name: "Gobi's Gold Weather Guard",
    brand: "Gobi's",
    category: "decorative",
    price: 4010,
    image: "/images/products/gobi's/gobi's gold weather guard.png",
    description: "Premium quality Gobi's Gold Weather Guard",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 41
  },
  {
    id: "gobis-gobi-s-summer-weather-shield",
    name: "Gobi's Summer Weather Shield",
    brand: "Gobi's",
    category: "decorative",
    price: 2062,
    image: "/images/products/gobi's/gobi's-Summer-Weather-Shield.png",
    description: "Premium quality Gobi's Summer Weather Shield",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 27
  },
  {
    id: "gobis-aqueous-matt-finish",
    name: "Aqueous Matt Finish",
    brand: "Gobi's",
    category: "decorative",
    price: 3557,
    image: "/images/products/gobi's/Gobis-Aqueous-Matt-Finish-253x253-removebg-preview.png",
    description: "Premium quality Aqueous Matt Finish",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 47
  },
  {
    id: "gobis-aqueous-wall-sealer",
    name: "Aqueous Wall Sealer",
    brand: "Gobi's",
    category: "decorative",
    price: 4100,
    image: "/images/products/gobi's/gobis-aqueous-wall-sealer-253x253-removebg-preview.png",
    description: "Premium quality Aqueous Wall Sealer",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 37
  },
  {
    id: "gobis-gloss-enamel",
    name: "Gloss Enamel",
    brand: "Gobi's",
    category: "decorative",
    price: 2579,
    image: "/images/products/gobi's/Gobis-Gloss-Enamel-253x253-removebg-preview.png",
    description: "Premium quality Gloss Enamel",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 22
  },
  {
    id: "gobis-gold-aqueous-matt-finish",
    name: "Gold Aqueous Matt Finish",
    brand: "Gobi's",
    category: "decorative",
    price: 4956,
    image: "/images/products/gobi's/Gobis-Gold-Aqueous-Matt-Finish-253x253-removebg-preview.png",
    description: "Premium quality Gold Aqueous Matt Finish",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 27
  },
  {
    id: "gobis-gold-enamel",
    name: "Gold Enamel",
    brand: "Gobi's",
    category: "decorative",
    price: 2891,
    image: "/images/products/gobi's/Gobis-Gold-Enamel-253x253-removebg-preview.png",
    description: "Premium quality Gold Enamel",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 36
  },
  {
    id: "gobis-gold-red-oxide-primer",
    name: "Gold Red Oxide Primer",
    brand: "Gobi's",
    category: "decorative",
    price: 2910,
    image: "/images/products/gobi's/Gobis-Gold-Red-Oxide-Primer-253x253-removebg-preview.png",
    description: "Premium quality Gold Red Oxide Primer",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 44
  },
  {
    id: "gobis-gold-undercoat",
    name: "Gold Undercoat",
    brand: "Gobi's",
    category: "decorative",
    price: 3973,
    image: "/images/products/gobi's/Gobis-Gold-Undercoat-253x253-removebg-preview.png",
    description: "Premium quality Gold Undercoat",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 39
  },
  {
    id: "gobis-gold-wall-emulsion",
    name: "Gold Wall Emulsion",
    brand: "Gobi's",
    category: "decorative",
    price: 4123,
    image: "/images/products/gobi's/Gobis-GOld-Wall-Emulsion-253x253-removebg-preview.png",
    description: "Premium quality Gold Wall Emulsion",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 38
  },
  {
    id: "gobis-gold-wall-putty",
    name: "Gold Wall Putty",
    brand: "Gobi's",
    category: "decorative",
    price: 4919,
    image: "/images/products/gobi's/Gobis-Gold-Wall-Putty-253x253-removebg-preview.png",
    description: "Premium quality Gold Wall Putty",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 49
  },
  {
    id: "gobis-premium-accessories",
    name: "Premium Accessories",
    brand: "Gobi's",
    category: "decorative",
    price: 3478,
    image: "/images/products/gobi's/Gobis-Premium-Accessories.png",
    description: "Premium quality Premium Accessories",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 24
  },
  {
    id: "gobis-red-oxide-primer-1",
    name: "Red Oxide Primer",
    brand: "Gobi's",
    category: "decorative",
    price: 3784,
    image: "/images/products/gobi's/Gobis-Red-Oxide-Primer-253x253-removebg-preview (1).png",
    description: "Premium quality Red Oxide Primer",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 33
  },
  {
    id: "gobis-red-oxide-primer-2",
    name: "Red Oxide Primer",
    brand: "Gobi's",
    category: "decorative",
    price: 2265,
    image: "/images/products/gobi's/Gobis-Red-Oxide-Primer-253x253-removebg-preview.png",
    description: "Premium quality Red Oxide Primer",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 36
  },
  {
    id: "gobis-silksheen-emulsion",
    name: "Silksheen Emulsion",
    brand: "Gobi's",
    category: "decorative",
    price: 3412,
    image: "/images/products/gobi's/Gobis-Silksheen-Emulsion-253x253-removebg-preview.png",
    description: "Premium quality Silksheen Emulsion",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 28
  },
  {
    id: "gobis-silverline-emulsion",
    name: "Silverline Emulsion",
    brand: "Gobi's",
    category: "decorative",
    price: 2761,
    image: "/images/products/gobi's/Gobis-Silverline-Emulsion-253x253.png",
    description: "Premium quality Silverline Emulsion",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 43
  },
  {
    id: "gobis-silverline-enamel",
    name: "Silverline Enamel",
    brand: "Gobi's",
    category: "decorative",
    price: 2768,
    image: "/images/products/gobi's/Gobis-Silverline-Enamel-253x253.png",
    description: "Premium quality Silverline Enamel",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 41
  },
  {
    id: "gobis-silverline-wall-putty",
    name: "Silverline Wall Putty",
    brand: "Gobi's",
    category: "decorative",
    price: 3059,
    image: "/images/products/gobi's/Gobis-Silverline-Wall-Putty-253x253.png",
    description: "Premium quality Silverline Wall Putty",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 33
  },
  {
    id: "gobis-silverline-wall-sealer",
    name: "Silverline Wall Sealer",
    brand: "Gobi's",
    category: "decorative",
    price: 2533,
    image: "/images/products/gobi's/Gobis-Silverline-Wall-Sealer-580x580.png",
    description: "Premium quality Silverline Wall Sealer",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 35
  },
  {
    id: "gobis-sona-lapi",
    name: "Sona Lapi",
    brand: "Gobi's",
    category: "decorative",
    price: 2418,
    image: "/images/products/gobi's/Gobis-Sona-Lapi-253x253-removebg-preview.png",
    description: "Premium quality Sona Lapi",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 23
  },
  {
    id: "gobis-summer-suprior-emulsion",
    name: "Summer Suprior Emulsion",
    brand: "Gobi's",
    category: "decorative",
    price: 3743,
    image: "/images/products/gobi's/Gobis-Summer-Suprior-Emulsion.png",
    description: "Premium quality Summer Suprior Emulsion",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 45
  },
  {
    id: "gobis-summer-wall-filling",
    name: "Summer Wall Filling",
    brand: "Gobi's",
    category: "decorative",
    price: 4445,
    image: "/images/products/gobi's/Gobis-Summer-Wall-Filling.png",
    description: "Premium quality Summer Wall Filling",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 23
  },
  {
    id: "gobis-summer-wall-sealer",
    name: "Summer Wall Sealer",
    brand: "Gobi's",
    category: "decorative",
    price: 3533,
    image: "/images/products/gobi's/Gobis-Summer-Wall-Sealer.png",
    description: "Premium quality Summer Wall Sealer",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 36
  },
  {
    id: "gobis-valmate-superior-emulsion",
    name: "Valmate Superior Emulsion",
    brand: "Gobi's",
    category: "decorative",
    price: 3654,
    image: "/images/products/gobi's/Gobis-Valmate-Superior-Emulsion.png",
    description: "Premium quality Valmate Superior Emulsion",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 45
  },
  {
    id: "gobis-valmate-wall-filling",
    name: "Valmate Wall Filling",
    brand: "Gobi's",
    category: "decorative",
    price: 2902,
    image: "/images/products/gobi's/Gobis-Valmate-Wall-Filling.png",
    description: "Premium quality Valmate Wall Filling",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 31
  },
  {
    id: "gobis-valmate-wall-sealer",
    name: "Valmate Wall Sealer",
    brand: "Gobi's",
    category: "decorative",
    price: 4006,
    image: "/images/products/gobi's/Gobis-valmate-Wall-Sealer.png",
    description: "Premium quality Valmate Wall Sealer",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 43
  },
  {
    id: "gobis-valmate-weather-shield",
    name: "Valmate Weather Shield",
    brand: "Gobi's",
    category: "decorative",
    price: 3460,
    image: "/images/products/gobi's/Gobis-Valmate-Weather-Shield.png",
    description: "Premium quality Valmate Weather Shield",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 30
  },
  {
    id: "gobis-wall-primer-sealer",
    name: "Wall Primer Sealer",
    brand: "Gobi's",
    category: "decorative",
    price: 2966,
    image: "/images/products/gobi's/Gobis-Wall-Primer-Sealer.png",
    description: "Premium quality Wall Primer Sealer",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 49
  },
  {
    id: "gobis-weather-protector",
    name: "Weather Protector",
    brand: "Gobi's",
    category: "decorative",
    price: 2999,
    image: "/images/products/gobi's/Gobis-Weather Protector.png",
    description: "Premium quality Weather Protector",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 31
  },
  {
    id: "gobis-gold-eggshell-matt-finish",
    name: "Gold Eggshell Matt Finish",
    brand: "Gobi's",
    category: "decorative",
    price: 4949,
    image: "/images/products/gobi's/gobis_gold_eggshell-matt-finish-253x253-removebg-preview.png",
    description: "Premium quality Gold Eggshell Matt Finish",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 42
  },
  {
    id: "gobis-heat-flex-sealent",
    name: "Heat Flex Sealent",
    brand: "Gobi's",
    category: "decorative",
    price: 2130,
    image: "/images/products/gobi's/heat flex sealent.png",
    description: "Premium quality Heat Flex Sealent",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 34
  },
  {
    id: "gobis-whatsapp-image-2026-02-21-at-1-14-16-am",
    name: "Whatsapp Image 2026 02 21 At 1.14.16 Am",
    brand: "Gobi's",
    category: "decorative",
    price: 4225,
    image: "/images/products/gobi's/WhatsApp_Image_2026-02-21_at_1.14.16_AM-removebg-preview.png",
    description: "Premium quality Whatsapp Image 2026 02 21 At 1.14.16 Am",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 30
  },
  {
    id: "gobis-whatsapp-image-2026-02-21-at-1-14-16-am-1",
    name: "Whatsapp Image 2026 02 21 At 1.14.16 Am 1",
    brand: "Gobi's",
    category: "decorative",
    price: 2367,
    image: "/images/products/gobi's/WhatsApp_Image_2026-02-21_at_1.14.16_AM__1_-removebg-preview.png",
    description: "Premium quality Whatsapp Image 2026 02 21 At 1.14.16 Am 1",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 40
  },
  {
    id: "gobis-whatsapp-image-2026-02-21-at-1-14-17-am",
    name: "Whatsapp Image 2026 02 21 At 1.14.17 Am",
    brand: "Gobi's",
    category: "decorative",
    price: 4383,
    image: "/images/products/gobi's/WhatsApp_Image_2026-02-21_at_1.14.17_AM-removebg-preview.png",
    description: "Premium quality Whatsapp Image 2026 02 21 At 1.14.17 Am",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 36
  },
  {
    id: "gobis-wood-finish-metal-finish",
    name: "Wood Finish Metal Finish",
    brand: "Gobi's",
    category: "decorative",
    price: 4760,
    image: "/images/products/gobi's/wood_finish__metal_finish-removebg-preview.png",
    description: "Premium quality Wood Finish Metal Finish",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 35
  },
  {
    id: "gobis-wood-sealer",
    name: "Wood Sealer",
    brand: "Gobi's",
    category: "decorative",
    price: 2237,
    image: "/images/products/gobi's/wood_sealer-removebg-preview.png",
    description: "Premium quality Wood Sealer",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 42
  },
  // Reliable Products
  {
    id: "reliable-enamel",
    name: "Enamel",
    brand: "Reliable",
    category: "decorative",
    price: 3819,
    image: "/images/products/Reliable/enamel.png",
    description: "Reliable quality Enamel",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 30
  },
  {
    id: "reliable-matt-finish-inner",
    name: "Matt Finish Inner",
    brand: "Reliable",
    category: "decorative",
    price: 3154,
    image: "/images/products/Reliable/Matt-Finish-Inner-630x630.png",
    description: "Reliable quality Matt Finish Inner",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 39
  },
  {
    id: "reliable-plastic-emulsion",
    name: "Plastic Emulsion",
    brand: "Reliable",
    category: "decorative",
    price: 4845,
    image: "/images/products/Reliable/plastic emulsion.png",
    description: "Reliable quality Plastic Emulsion",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 36
  },
  {
    id: "reliable-plastic-priemer-sealer",
    name: "Plastic Priemer Sealer",
    brand: "Reliable",
    category: "decorative",
    price: 2574,
    image: "/images/products/Reliable/plastic priemer sealer.png",
    description: "Reliable quality Plastic Priemer Sealer",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 24
  },
  {
    id: "reliable-plastic-emulsion-special-shade",
    name: "Plastic Emulsion Special Shade",
    brand: "Reliable",
    category: "decorative",
    price: 2788,
    image: "/images/products/Reliable/Plastic-Emulsion-Special-Shade-630x630-removebg-preview.png",
    description: "Reliable quality Plastic Emulsion Special Shade",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 37
  },
  {
    id: "reliable-red-oxide-wood-and-metal",
    name: "Red Oxide Wood And Metal",
    brand: "Reliable",
    category: "decorative",
    price: 4053,
    image: "/images/products/Reliable/Red-Oxide-wood-and-metal-630x630-removebg-preview.png",
    description: "Reliable quality Red Oxide Wood And Metal",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 41
  },
  {
    id: "reliable-warnish",
    name: "Warnish",
    brand: "Reliable",
    category: "decorative",
    price: 4573,
    image: "/images/products/Reliable/Warnish-630x630.png",
    description: "Reliable quality Warnish",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 34
  },
  {
    id: "reliable-water-matt-1",
    name: "Water Matt 1",
    brand: "Reliable",
    category: "decorative",
    price: 3651,
    image: "/images/products/Reliable/Water-Matt-1-1024x657-removebg-preview.png",
    description: "Reliable quality Water Matt 1",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 21
  },
  {
    id: "reliable-weather-protector",
    name: "Weather Protector",
    brand: "Reliable",
    category: "decorative",
    price: 3838,
    image: "/images/products/Reliable/weather protector.png",
    description: "Reliable quality Weather Protector",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 43
  },
  {
    id: "reliable-whatsapp-image-2024-11-18-at-15-08-00",
    name: "Whatsapp Image 2024 11 18 At 15.08.00",
    brand: "Reliable",
    category: "decorative",
    price: 3482,
    image: "/images/products/Reliable/WhatsApp-Image-2024-11-18-at-15.08.00-1024x656-removebg-preview.png",
    description: "Reliable quality Whatsapp Image 2024 11 18 At 15.08.00",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 30
  },
  {
    id: "reliable-whatsapp-image-2026-02-21-at-1-14-18-am",
    name: "Whatsapp Image 2026 02 21 At 1.14.18 Am",
    brand: "Reliable",
    category: "decorative",
    price: 2191,
    image: "/images/products/Reliable/WhatsApp_Image_2026-02-21_at_1.14.18_AM-removebg-preview.png",
    description: "Reliable quality Whatsapp Image 2026 02 21 At 1.14.18 Am",
    coverage: "100-120 sq ft/liter",
    finishType: "Standard",
    inStock: true,
    loyaltyPoints: 47
  },
];

export const WHATSAPP_NUMBER = '923001234567'; // Replace with actual number

export const loyaltyTiers = {
  bronze: { min: 0, max: 999, discount: 2, pointMultiplier: 1 },
  silver: { min: 1000, max: 4999, discount: 5, pointMultiplier: 1.25 },
  gold: { min: 5000, max: 9999, discount: 8, pointMultiplier: 1.5 },
  platinum: { min: 10000, max: Infinity, discount: 12, pointMultiplier: 2 },
};
